# TODO 4: Add prod properties.
spring:
  config:
    activate:
      on-profile: prod

  application:
    name: spring-profiles-prod

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/serviceup
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: new_user
#    expression is Springâ€™s placeholder syntax with a built-in default value "password"
    password: ${MYSQL_PASS:password}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 300000
      pool-name: HikariProdPool

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    root: INFO
    io.theja: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, info, beans, metrics


# -Dspring.profiles.active=prod -DMYSQL_PASS=strong_password