# TODO 20: Add payment-service properties.
spring:
  application:
    name: payment-service
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:payments;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        processOrder-in-0:
          destination: order-created
        paymentProcessed-out-0:
          destination: payment-processed
        paymentFailed-out-0:
          destination: payment-failed
    function:
      definition: processOrder

server:
  port: 8082
