# TODO 13: Add order-service properties.
spring:
  application:
    name: order-service
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:orders;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        # orderCreated - Output binding name for a function that publishes order-created messages.
        # out - binding direction - sending.
        # 0 - index of the channel when a function has multiple inputs or outputs.
        orderCreated-out-0:
          # Kafka topic name
          destination: order-created
        # Input binding name for a function that consumes messages when payments are processed.
        paymentProcessed-in-0:
          destination: payment-processed
        # Input binding name for a function that consumes messages when payments fail.
        paymentFailed-in-0:
          destination: payment-failed
    function:
    # Spring will register them as available functions and map bindings to the functions by matching function names to binding prefixes if you rely on the default naming conventions.
      definition: paymentProcessed;paymentFailed

server:
  port: 8081

#Flow
#Order Service
#  EventHandlers
#    paymentProcessed()
#    paymentFailed()
#  OrderController
#    Send event to 'orderCreated-out-0'.
#
#Payment Service
#  PaymentConsumer
#    processOrder()
#      Send event to 'paymentFailed-out-0 / paymentProcessed-out-0'.
