# TODO 11: Add query-service properties.
spring:
  application:
    name: query-service
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:querydb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        productCreated-in-0:
          destination: product-created
        productUpdated-in-0:
          destination: product-updated
    function:
      definition: productCreated;productUpdated

server:
  port: 8082
